export { localStorage } from "./localStorage";
export { sessionStorage } from "./sessionStorage";
export { cookieStorage } from "./cookieStorage";
export { memoryStorage } from "./memoryStorage";
export { vuexStorage } from "./vuexStorage";
export { piniaStorage } from "./piniaStorage";
export { gunStorage } from "./gunStorage";
export { secureStorage } from "./secureStorage";
export { configStorage } from "./configStorage";
