dependencies:
  - changed-files:
      - any-glob-to-any-file:
          ["package.json", "pnpm-lock.yaml", "package-lock.json", "yarn.lock"]

ci:
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/**"]

docs:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]
