import { localStorage } from "./_stores/localStorage";
import { sessionStorage } from "./_stores/sessionStorage";
import { cookieStorage } from "./_stores/cookieStorage";
import { memoryStorage } from "./_stores/memoryStorage";
import { vuexStorage } from "./_stores/vuexStorage";
import { piniaStorage } from "./_stores/piniaStorage";
import { gunStorage } from "./_stores/gunStorage";
import { secureStorage } from "./_stores/secureStorage";
import { configStorage } from "./_stores/configStorage";
import { signalStorage } from "./_stores/signalStorage";
export type Tconfig = typeof configStorage;
export type Tcookie = typeof cookieStorage;
export type Tgun = typeof gunStorage;
export type Tlocal = typeof localStorage;
export type Tmemory = typeof memoryStorage;
export type Tpinia = typeof piniaStorage;
export type Tsecure = typeof secureStorage;
export type Tsession = typeof sessionStorage;
export type Tvuex = typeof vuexStorage;
export type Tsignal = typeof signalStorage;
export type TypeUstore = {
    config: Tconfig;
    cookie: Tcookie;
    gun: Tgun;
    local: Tlocal;
    memory: Tmemory;
    pinia: Tpinia;
    secure: Tsecure;
    session: Tsession;
    vuex: Tvuex;
    signal: Tsignal;
};
export declare const uStore: TypeUstore;
export default uStore;
export { localStorage };
export { sessionStorage };
export { cookieStorage };
export { memoryStorage };
export { vuexStorage };
export { piniaStorage };
export { gunStorage };
export { secureStorage };
export { configStorage };
export { signalStorage };
//# sourceMappingURL=index.d.ts.map