"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.webqlStorage = exports.idbStorage = exports.Config = exports.configStorage = exports.secureStorage = exports.gunStorage = exports.createApp = exports.defineStore = exports.createPinia = exports.piniaStorage = exports.vuexStorage = exports.memoryStorage = exports.cookieStorage = exports.sessionStorage = exports.localStorage = exports.app = void 0;
const localStorage_1 = require("./localStorage");
Object.defineProperty(exports, "localStorage", { enumerable: true, get: function () { return localStorage_1.localStorage; } });
const sessionStorage_1 = require("./sessionStorage");
Object.defineProperty(exports, "sessionStorage", { enumerable: true, get: function () { return sessionStorage_1.sessionStorage; } });
const cookieStorage_1 = require("./cookieStorage");
Object.defineProperty(exports, "cookieStorage", { enumerable: true, get: function () { return cookieStorage_1.cookieStorage; } });
const memoryStorage_1 = require("./memoryStorage");
Object.defineProperty(exports, "memoryStorage", { enumerable: true, get: function () { return memoryStorage_1.memoryStorage; } });
const vuexStorage_1 = require("./vuexStorage");
Object.defineProperty(exports, "vuexStorage", { enumerable: true, get: function () { return vuexStorage_1.vuexStorage; } });
const piniaStorage_1 = require("./piniaStorage");
Object.defineProperty(exports, "piniaStorage", { enumerable: true, get: function () { return piniaStorage_1.piniaStorage; } });
const piniaStorage_2 = require("./piniaStorage");
Object.defineProperty(exports, "createPinia", { enumerable: true, get: function () { return piniaStorage_2.createPinia; } });
const piniaStorage_3 = require("./piniaStorage");
Object.defineProperty(exports, "defineStore", { enumerable: true, get: function () { return piniaStorage_3.defineStore; } });
const uStoreStorage_1 = require("./uStoreStorage");
Object.defineProperty(exports, "createApp", { enumerable: true, get: function () { return uStoreStorage_1.createApp; } });
const gunStorage_1 = require("./gunStorage");
Object.defineProperty(exports, "gunStorage", { enumerable: true, get: function () { return gunStorage_1.gunStorage; } });
const secureStorage_1 = require("./secureStorage");
Object.defineProperty(exports, "secureStorage", { enumerable: true, get: function () { return secureStorage_1.secureStorage; } });
const configStorage_1 = require("./configStorage");
Object.defineProperty(exports, "configStorage", { enumerable: true, get: function () { return configStorage_1.configStorage; } });
const configStorage_2 = require("./configStorage");
Object.defineProperty(exports, "Config", { enumerable: true, get: function () { return configStorage_2.Config; } });
const idbStorage_1 = require("./idbStorage");
Object.defineProperty(exports, "idbStorage", { enumerable: true, get: function () { return idbStorage_1.idbStorage; } });
const webqlStorage_1 = require("./webqlStorage");
Object.defineProperty(exports, "webqlStorage", { enumerable: true, get: function () { return webqlStorage_1.webqlStorage; } });
exports.app = (0, uStoreStorage_1.createApp)({});
//# sourceMappingURL=index.js.map