import { localStorage } from "./localStorage";
import { sessionStorage } from "./sessionStorage";
import { cookieStorage } from "./cookieStorage";
import { memoryStorage } from "./memoryStorage";
import { vuexStorage } from "./vuexStorage";
import { piniaStorage } from "./piniaStorage";
import { createPinia } from "./piniaStorage";
import { defineStore } from "./piniaStorage";
import { createApp } from "./uStoreStorage";
import { gunStorage } from "./gunStorage";
import { secureStorage } from "./secureStorage";
import { configStorage } from "./configStorage";
import { Config } from "./configStorage";
import { idbStorage } from "./idbStorage";
import { webqlStorage } from "./webqlStorage";
export declare const app: import("vue").App<Element>;
export { localStorage };
export { sessionStorage };
export { cookieStorage };
export { memoryStorage };
export { vuexStorage };
export { piniaStorage };
export { createPinia };
export { defineStore };
export { createApp };
export { gunStorage };
export { secureStorage };
export { configStorage };
export { Config };
export { idbStorage };
export { webqlStorage };
//# sourceMappingURL=index.d.ts.map